const ALL_CONTENT = [
  // 🎬 FILMLER
  {
    key: 'movie-533535',
    type: 'movie',
    title: 'Deadpool & Wolverine',
    original_title: 'Deadpool & Wolverine',
    tagline: 'Herkes mutlu bir sonu hak eder.',
    overview: 'TVA tarafından göreve çağrılan umutsuz Wade Wilson, çoklu evrenin tehlikeye girmesiyle birlikte isteksiz bir Wolverine ile güçlerini birleştirmek zorunda kalır.',
    poster: 'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg',
    rating: 8.0,
    year: '2024',
    duration: 128,
    genres: ['Aksiyon', 'Komedi', 'Bilim-Kurgu'],
    status: 'Released',
    trailer: 'https://www.youtube.com/watch?v=73_1biulkYk',
    categories: ['popular']
  },
  {
    key: 'movie-693134',
    type: 'movie',
    title: 'Dune: Çöl Gezegeni Bölüm İki',
    original_title: 'Dune: Part Two',
    tagline: 'Kader bir lider gerektirir.',
    overview: 'Paul Atreides, ailesini yok eden komploculara karşı intikam arayışındayken Chani ve Fremenlerle güçlerini birleştirir.',
    poster: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/xOMo8BRK7PfcJv9JCnx7s5hj0x2.jpg',
    rating: 8.8,
    year: '2024',
    duration: 166,
    genres: ['Bilim-Kurgu', 'Macera', 'Aksiyon'],
    status: 'Released',
    trailer: 'https://www.youtube.com/watch?v=Way9Dexny3w',
    categories: ['popular', 'most_watched']
  },
  {
    key: 'movie-1022789',
    type: 'movie',
    title: 'Ters Yüz 2 (Inside Out 2)',
    original_title: 'Inside Out 2',
    tagline: 'Yeni duygulara yer açın.',
    overview: 'Artık bir ergen olan Riley\'nin zihin merkezinde ani bir tadilat başlar ve beklenmedik yeni duygular içeri girer: Kaygı, Gıpta, Utanç ve Bıkkınlık!',
    poster: 'https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/xg27NrXi7EgDXUrHVOf7Y8i9Ce8.jpg',
    rating: 8.1,
    year: '2024',
    duration: 96,
    genres: ['Animasyon', 'Aile', 'Macera', 'Komedi'],
    status: 'Released',
    trailer: 'https://www.youtube.com/watch?v=LEjhY15eCx0',
    categories: ['popular']
  },
  {
    key: 'movie-945961',
    type: 'movie',
    title: 'Alien: Romulus',
    original_title: 'Alien: Romulus',
    tagline: 'Uzayda kimse çığlığınızı duyamaz.',
    overview: 'Terk edilmiş bir uzay istasyonunun derinliklerini temizleyen bir grup genç uzay kolonisti, evrendeki en korkunç yaşam formuyla yüz yüze gelir.',
    poster: 'https://image.tmdb.org/t/p/w500/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg',
    rating: 7.9,
    year: '2024',
    duration: 119,
    genres: ['Korku', 'Bilim-Kurgu', 'Gerilim'],
    status: 'Released',
    trailer: 'https://www.youtube.com/watch?v=x0XDEhP4MQs',
    categories: ['popular']
  },
  {
    key: 'movie-933260',
    type: 'movie',
    title: 'Cevher (The Substance)',
    original_title: 'The Substance',
    tagline: 'Kendinizin daha iyi bir versiyonunu hayal edin.',
    overview: 'Gözden düşen eski bir ünlü yıldız, hücre bölünmesini hızlandırarak kendisinin daha genç, daha güzel ve daha mükemmel bir versiyonunu yaratan gizemli bir karaborsa ilacını dener.',
    poster: 'https://image.tmdb.org/t/p/w500/lqoMzCcZYEFK729Fc6rRII1ukMt.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/7h65Np3zChgQFiWdpzKdbL5Fcwt.jpg',
    rating: 7.9,
    year: '2024',
    duration: 141,
    genres: ['Korku', 'Dram', 'Bilim-Kurgu'],
    status: 'Released',
    trailer: 'https://www.youtube.com/watch?v=LNlrGhPBNKc',
    categories: ['trending']
  },
  {
    key: 'movie-1184918',
    type: 'movie',
    title: 'Vahşi Robot (The Wild Robot)',
    original_title: 'The Wild Robot',
    tagline: 'Bazen hayatta kalmak için programlandığınız şeyden fazlası olmalısınız.',
    overview: 'Issız bir adaya düşen ROZZUM ünitesi 7134 ("Roz"), adadaki vahşi hayvanlarla bağ kurarak çevreye uyum sağlamayı öğrenir.',
    poster: 'https://image.tmdb.org/t/p/w500/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/mQZJoIhTE5Zc.jpg',
    rating: 8.6,
    year: '2024',
    duration: 102,
    genres: ['Animasyon', 'Bilim-Kurgu', 'Aile', 'Macera'],
    status: 'Released',
    trailer: 'https://www.youtube.com/watch?v=67vbA5ZJdKQ',
    categories: ['trending']
  },
  {
    key: 'movie-558449',
    type: 'movie',
    title: 'Gladyatör II (Gladiator II)',
    original_title: 'Gladiator II',
    tagline: 'Küllerinden yeniden doğan bir imparatorluk.',
    overview: 'Maximus\'un ölümünden yıllar sonra, Lucilla\'nın oğlu Lucius, Roma\'nın tiran imparatorlarına karşı Kolezyum arenasında özgürlük savaşı verir.',
    poster: 'https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/euYIwmwkmz95mnXvufwnb9.jpg',
    rating: 7.7,
    year: '2024',
    duration: 148,
    genres: ['Aksiyon', 'Dram', 'Macera', 'Tarih'],
    status: 'Released',
    trailer: 'https://www.youtube.com/watch?v=4rgYUipGJNo',
    categories: ['new']
  },
  {
    key: 'movie-889737',
    type: 'movie',
    title: 'Joker: İkili Delilik (Joker: Folie à Deux)',
    original_title: 'Joker: Folie à Deux',
    tagline: 'Dünya artık bir sahne.',
    overview: 'Arthur Fleck, Arkham Eyalet Hastanesi\'nde yargılanmayı beklerken gerçek aşkı Harley Quinn ve içindeki müziği keşfeder.',
    poster: 'https://image.tmdb.org/t/p/w500/aciP8Km0waTLsq1ovJnIhXU966m.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/v9acaNu.jpg',
    rating: 6.8,
    year: '2024',
    duration: 138,
    genres: ['Dram', 'Suç', 'Gerilim', 'Müzik'],
    status: 'Released',
    trailer: 'https://www.youtube.com/watch?v=_OKAwz2NiOI',
    categories: ['new']
  },
  {
    key: 'movie-872585',
    type: 'movie',
    title: 'Oppenheimer',
    original_title: 'Oppenheimer',
    tagline: 'Dünya sonsuza dek değişti.',
    overview: 'J. Robert Oppenheimer\'ın Manhattan Projesi liderliğindeki atom bombasının geliştirilme sürecini konu alıyor.',
    poster: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    rating: 8.9,
    year: '2023',
    duration: 180,
    genres: ['Dram', 'Tarih', 'Biyografi'],
    status: 'Released',
    trailer: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
    categories: ['top_rated', 'most_watched']
  },
  {
    key: 'movie-157336',
    type: 'movie',
    title: 'Yıldızlararası (Interstellar)',
    original_title: 'Interstellar',
    tagline: 'İnsanlığın sonu bizim sonumuz olmak zorunda değil.',
    overview: 'İnsanlığın tükenme tehlikesiyle karşı karşıya olduğu bir gelecekte solucan deliğinden geçen bir keşif ekibinin yolculuğu.',
    poster: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    rating: 8.7,
    year: '2014',
    duration: 169,
    genres: ['Bilim-Kurgu', 'Dram', 'Macera'],
    status: 'Released',
    trailer: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
    categories: ['top_rated', 'most_watched']
  },

  // 📺 DIZILER
  {
    key: 'tv-126308',
    type: 'tv',
    title: 'Şogun (Shōgun)',
    original_title: 'Shōgun',
    tagline: 'Kader kılıcın ucundadır.',
    overview: '1600 yılında feodal Japonya\'da Lord Toranaga ve bir İngiliz denizcinin destansı ittifakı.',
    poster: 'https://image.tmdb.org/t/p/w500/7O4iVfOMQmdCSPx7DYGvx2m08i.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/zW0v2YT7x.jpg',
    rating: 8.9,
    year: '2024',
    duration: 60,
    number_of_seasons: 1,
    number_of_episodes: 10,
    genres: ['Dram', 'Tarih', 'Savaş'],
    status: 'Returning Series',
    trailer: 'https://www.youtube.com/watch?v=yAN5uspAoT4',
    categories: ['popular', 'most_watched']
  },
  {
    key: 'tv-106379',
    type: 'tv',
    title: 'Fallout',
    original_title: 'Fallout',
    tagline: 'Kıyamet sonrası dünyaya hoş geldiniz.',
    overview: 'Nükleer kıyametten 200 yıl sonra sığınaktan çıkan Lucy\'nin vahşi çorak topraklardaki macerası.',
    poster: 'https://image.tmdb.org/t/p/w500/AnsSKR9LuK0T9bAILVaipUt3q39.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/nQhK8.jpg',
    rating: 8.6,
    year: '2024',
    duration: 60,
    number_of_seasons: 2,
    number_of_episodes: 16,
    genres: ['Bilim-Kurgu', 'Aksiyon', 'Macera'],
    status: 'Returning Series',
    trailer: 'https://www.youtube.com/watch?v=V-mugKDQDlg',
    categories: ['popular']
  },
  {
    key: 'tv-124834',
    type: 'tv',
    title: 'The Penguin',
    original_title: 'The Penguin',
    tagline: 'Gotham\'ın yeraltı dünyası el değiştiriyor.',
    overview: 'Oz Cobb, Gotham City\'nin suç imparatorluğunun kontrolünü ele geçirmek için hamle yapar.',
    poster: 'https://image.tmdb.org/t/p/w500/vOWOuRkF7A6dC9mB3uN.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/kC1.jpg',
    rating: 8.8,
    year: '2024',
    duration: 55,
    number_of_seasons: 1,
    number_of_episodes: 8,
    genres: ['Suç', 'Dram'],
    status: 'Ended',
    trailer: 'https://www.youtube.com/watch?v=sfJG6hDCfec',
    categories: ['trending']
  },
  {
    key: 'tv-1396',
    type: 'tv',
    title: 'Breaking Bad',
    original_title: 'Breaking Bad',
    tagline: 'Tüm kuralları yık.',
    overview: 'Kanser teşhisi konan bir lise kimya öğretmeni metamfetamin üretmeye başlar.',
    poster: 'https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
    rating: 9.5,
    year: '2008',
    duration: 47,
    number_of_seasons: 5,
    number_of_episodes: 62,
    genres: ['Dram', 'Suç', 'Gerilim'],
    status: 'Ended',
    trailer: 'https://www.youtube.com/watch?v=HhesaQXLuRY',
    categories: ['top_rated', 'most_watched']
  },

  // 🎌 ANIME
  {
    key: 'anime-52299',
    type: 'anime',
    title: 'Solo Leveling',
    original_title: 'Solo Leveling',
    tagline: 'En zayıf avcıdan en güçlü gölge lorduna.',
    overview: 'Sung Jinwoo ölümden döndükten sonra seviye atlama sisteminin sahibi olur.',
    poster: 'https://cdn.myanimelist.net/images/anime/1170/141042.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/8BQXd4nU9p5wM8h.jpg',
    rating: 8.9,
    year: '2024',
    duration: 24,
    number_of_seasons: 2,
    number_of_episodes: 24,
    genres: ['Aksiyon', 'Macera', 'Fantastik'],
    status: 'Returning Series',
    trailer: 'https://www.youtube.com/watch?v=s8cR_G4m37s',
    categories: ['popular', 'most_watched']
  },
  {
    key: 'anime-52991',
    type: 'anime',
    title: 'Frieren: Yolculuğun Sonu',
    original_title: 'Sousou no Frieren',
    tagline: 'Zaman akıp gider, hatıralar kalır.',
    overview: 'Elf büyücü Frieren\'in insanlığı anlamak için çıktığı duygusal yolculuk.',
    poster: 'https://cdn.myanimelist.net/images/anime/1015/138006.jpg',
    backdrop: null,
    rating: 9.4,
    year: '2024',
    duration: 24,
    number_of_seasons: 1,
    number_of_episodes: 28,
    genres: ['Macera', 'Dram', 'Fantastik'],
    status: 'Ended',
    trailer: 'https://www.youtube.com/watch?v=qgQunxD0qMo',
    categories: ['popular', 'top_rated']
  },
  {
    key: 'anime-54744',
    type: 'anime',
    title: 'Kaiju No. 8',
    original_title: 'Kaiju No. 8',
    tagline: 'İçindeki canavarla insanlığı koru.',
    overview: 'Canavar temizleme işçisi Kafka Hibino\'nun bir insansı kaijuya dönüşmesi.',
    poster: 'https://cdn.myanimelist.net/images/anime/1066/141973.jpg',
    backdrop: null,
    rating: 8.4,
    year: '2024',
    duration: 24,
    number_of_seasons: 1,
    number_of_episodes: 12,
    genres: ['Aksiyon', 'Bilim-Kurgu'],
    status: 'Returning Series',
    trailer: 'https://www.youtube.com/watch?v=c3ljvTq1lPQ',
    categories: ['trending', 'new']
  },
  {
    key: 'anime-16498',
    type: 'anime',
    title: 'Titan\'a Saldırı (Attack on Titan)',
    original_title: 'Shingeki no Kyojin',
    tagline: 'Eğer kazanırsak yaşarız.',
    overview: 'Devasa insansı Titanlara karşı surların içinde verilen varoluş mücadelesi.',
    poster: 'https://cdn.myanimelist.net/images/anime/10/47347.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/8BQXd4nU9p5wM8h.jpg',
    rating: 9.2,
    year: '2013',
    duration: 24,
    number_of_seasons: 4,
    number_of_episodes: 89,
    genres: ['Aksiyon', 'Fantastik', 'Dram', 'Gizem'],
    status: 'Ended',
    trailer: 'https://www.youtube.com/watch?v=MGRm4IzK1SQ',
    categories: ['top_rated', 'most_watched']
  }
];

module.exports = { ALL_CONTENT };
