const FALLBACK_CONTENT = [
  {
    key: 'movie-872585',
    type: 'movie',
    title: 'Oppenheimer',
    original_title: 'Oppenheimer',
    tagline: 'Dünya sonsuza dek değişti.',
    overview: 'J. Robert Oppenheimer\'ın Manhattan Projesi liderliğindeki atom bombasının geliştirilme sürecini ve sonrasında yaşadığı ahlaki ve politik sınavı konu alıyor.',
    poster: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    rating: 8.9,
    year: '2023',
    duration: 180,
    genres: ['Dram', 'Tarih', 'Biyografi'],
    status: 'Released',
    trailer: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
    categories: ['popular', 'trending', 'top_rated', 'most_watched']
  },
  {
    key: 'movie-157336',
    type: 'movie',
    title: 'Yıldızlararası',
    original_title: 'Interstellar',
    tagline: 'İnsanlığın sonu bizim sonumuz olmak zorunda değil.',
    overview: 'İnsanlığın tükenme tehlikesiyle karşı karşıya olduğu bir gelecekte, bir grup kaşif insanlık için yeni bir yuva bulmak amacıyla bir solucan deliğinden geçerek galaksiler arası bir yolculuğa çıkar.',
    poster: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    rating: 8.7,
    year: '2014',
    duration: 169,
    genres: ['Bilim-Kurgu', 'Dram', 'Macera'],
    status: 'Released',
    trailer: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
    categories: ['popular', 'top_rated', 'most_watched']
  },
  {
    key: 'movie-693134',
    type: 'movie',
    title: 'Dune: Çöl Gezegeni Bölüm İki',
    original_title: 'Dune: Part Two',
    tagline: 'Kader bir lider gerektirir.',
    overview: 'Paul Atreides, ailesini yok eden komploculara karşı intikam arayışındayken Chani ve Fremenlerle güçlerini birleştirir.',
    poster: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/xOMo8BRK7PfcJv9JCnx7s5hj0x2.jpg',
    rating: 8.8,
    year: '2024',
    duration: 166,
    genres: ['Bilim-Kurgu', 'Macera', 'Aksiyon'],
    status: 'Released',
    trailer: 'https://www.youtube.com/watch?v=Way9Dexny3w',
    categories: ['popular', 'trending', 'new', 'top_rated', 'most_watched']
  },
  {
    key: 'movie-27205',
    type: 'movie',
    title: 'Başlangıç',
    original_title: 'Inception',
    tagline: 'Zihniniz suç mahallidir.',
    overview: 'Dom Cobb, insanların rüyalarından bilinçaltı sırlarını çalan çok yetenekli bir hırsızdır. Ona bu sefer bir fikri çalmak değil, zihne eklemek görevi verilir.',
    poster: 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/8ZTVqvKDQ8emSGUEMjsS4yR84zT.jpg',
    rating: 8.8,
    year: '2010',
    duration: 148,
    genres: ['Bilim-Kurgu', 'Aksiyon', 'Macera'],
    status: 'Released',
    trailer: 'https://www.youtube.com/watch?v=YoHD9XEInc0',
    categories: ['popular', 'top_rated', 'most_watched']
  },
  {
    key: 'movie-155',
    type: 'movie',
    title: 'Kara Şövalye',
    original_title: 'The Dark Knight',
    tagline: 'Kaosun dünyasında tek kural hayatta kalmaktır.',
    overview: 'Batman, Teğmen Gordon ve Savcı Harvey Dent yardımıyla Gotham sokaklarını suçtan arındırmaya başlar. Ancak Joker\'in ortaya çıkışı şehri dehşete sürükler.',
    poster: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
    rating: 9.0,
    year: '2008',
    duration: 152,
    genres: ['Aksiyon', 'Suç', 'Dram'],
    status: 'Released',
    trailer: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    categories: ['popular', 'trending', 'top_rated', 'most_watched']
  },
  {
    key: 'tv-1396',
    type: 'tv',
    title: 'Breaking Bad',
    original_title: 'Breaking Bad',
    tagline: 'Tüm kuralları yık.',
    overview: 'Kanser teşhisi konan bir lise kimya öğretmeni, ailesinin geleceğini güvence altına almak için eski bir öğrencisiyle birlikte metamfetamin üretip satmaya başlar.',
    poster: 'https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
    rating: 9.5,
    year: '2008',
    duration: 47,
    number_of_seasons: 5,
    number_of_episodes: 62,
    genres: ['Dram', 'Suç', 'Gerilim'],
    status: 'Ended',
    trailer: 'https://www.youtube.com/watch?v=HhesaQXLuRY',
    categories: ['popular', 'trending', 'top_rated', 'most_watched']
  },
  {
    key: 'tv-94605',
    type: 'tv',
    title: 'Arcane',
    original_title: 'Arcane',
    tagline: 'İki şehir, iki kardeş, tek bir kader.',
    overview: 'Ütopik Piltover şehri ile baskı altındaki Zaun arasındaki sert çatışmada iki ikonik şampiyon kardeş, karşı saflarda savaşmak zorunda kalır.',
    poster: 'https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn396mlX3Yq1m.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/hPe0F1K6X1P2pXnQ6tT4.jpg',
    rating: 9.1,
    year: '2021',
    duration: 40,
    number_of_seasons: 2,
    number_of_episodes: 18,
    genres: ['Animasyon', 'Aksiyon', 'Macera', 'Fantastik'],
    status: 'Returning Series',
    trailer: 'https://www.youtube.com/watch?v=fXmAurh012s',
    categories: ['popular', 'trending', 'new', 'top_rated', 'most_watched']
  },
  {
    key: 'anime-16498',
    type: 'anime',
    title: 'Titan\'a Saldırı (Shingeki no Kyojin)',
    original_title: 'Attack on Titan',
    tagline: 'Eğer kazanırsak yaşarız. Savaşmazsak kazanamayız.',
    overview: 'İnsanlık, devasa insansı canavarlar olan Titanlardan korunmak için üç devasa surun içine sığınmıştır. Eren Yeager ailesini kaybettikten sonra tüm Titanları yok etmeye yemin eder.',
    poster: 'https://cdn.myanimelist.net/images/anime/10/47347.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/8BQXd4nU9p5wM8h.jpg',
    rating: 9.2,
    year: '2013',
    duration: 24,
    number_of_seasons: 4,
    number_of_episodes: 89,
    genres: ['Aksiyon', 'Fantastik', 'Dram', 'Gizem'],
    status: 'Ended',
    trailer: 'https://www.youtube.com/watch?v=MGRm4IzK1SQ',
    categories: ['popular', 'trending', 'top_rated', 'most_watched']
  },
  {
    key: 'anime-52991',
    type: 'anime',
    title: 'Frieren: Yolculuğun Sonu',
    original_title: 'Sousou no Frieren',
    tagline: 'Zaman akıp gider, hatıralar kalır.',
    overview: 'Şeytan Kralı yenen kahraman partisinin büyücüsü olan elf Frieren, ölümsüz ömrünün insan arkadaşlarının ölümleriyle nasıl değiştiğini keşfetmek için yeni bir yolculuğa çıkar.',
    poster: 'https://cdn.myanimelist.net/images/anime/1015/138006.jpg',
    backdrop: null,
    rating: 9.4,
    year: '2023',
    duration: 24,
    number_of_seasons: 1,
    number_of_episodes: 28,
    genres: ['Macera', 'Dram', 'Fantastik'],
    status: 'Ended',
    trailer: 'https://www.youtube.com/watch?v=qgQunxD0qMo',
    categories: ['popular', 'trending', 'new', 'top_rated', 'most_watched']
  }
];

function getTrendingFallback(type = 'movie', filter = 'popular', page = 1, limit = 20) {
  const filtered = FALLBACK_CONTENT.filter(item => {
    if (type !== 'all' && item.type !== type) return false;
    return true;
  });
  const offset = (page - 1) * limit;
  return {
    results: filtered.slice(offset, offset + limit),
    total: filtered.length,
    hasMore: offset + limit < filtered.length,
    source: 'fallback'
  };
}

module.exports = { FALLBACK_CONTENT, getTrendingFallback };
